version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: freeauditor_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: freeauditor
      POSTGRES_USER: freeauditor
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - freeauditor

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: freeauditor_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - freeauditor

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: freeauditor_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://freeauditor:password123@postgres:5432/freeauditor
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-key
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - freeauditor
    command: npm run start:dev

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: freeauditor_frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
      REACT_APP_ENVIRONMENT: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - freeauditor
    command: npm start

  # MinIO for S3-compatible storage (development)
  minio:
    image: minio/minio:latest
    container_name: freeauditor_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: freeauditor
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - freeauditor
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  freeauditor:
    driver: bridge